---
- name: Provision the EC2 Server
# ==============================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    regions:
      "1": "us-east-1"
      "2": "us-west-1"
      "3": "us-west-2"
      "4": "eu-west-1"
      "5": "eu-central-1"
      "6": "ap-northeast-1"
      "7": "ap-northeast-2"
      "8": "ap-southeast-1"
      "9": "ap-southeast-2"
      "10": "ap-south-1"
      "11": "sa-east-1"

  # These variable files are included so the ec2-security-group role
  # knows which ports to open
  vars_files:
    - roles/ssh/defaults/main.yml

  vars_prompt:
    - name: "aws_region_var"
      prompt: |
        In what region should the server be located?
          1.  US East        (N. Virginia)
          2.  US West        (N.California)
          3.  US West        (Oregon)
          4.  EU             (Ireland)
          5.  EU             (Frankfurt)
          6.  Asia Pacific   (Tokyo)
          7.  Asia Pacific   (Seoul)
          8.  Asia Pacific   (Singapore)
          9.  Asia Pacific   (Sydney)
          10. Asia Pacific   (Mumbai)
          11. South America  (Sao Paulo)
        Please select your region by typing the number and pressing enter. Press enter for the default region (#1).
      default: "1"
      private: no

    - name: "aws_vpc_id_var"
      prompt: |

        Please enter a name for the VPC you would like to SpinUp a Server/Security Group
        (e.g. vpc-442f354ee)?

        Press enter to use the default VPC name.
      private: no

    - name: "aws_vpc_subnet_id_var"
      prompt: |

        Please enter the name the subnet for the server.
        (e.g. subnet-82d3e434)

        Press enter to use the default subnet name.
      private: no

    - name: "aws_instance_name"
      prompt: "\nPlease enter a name for the server. Press enter to use the default name (spinup)\n"
      default: "spinup"
      private: no

    - name: "aws_access_key"
      prompt: "\n\nThe following information can be found in the IAM Management Console.
https://console.aws.amazon.com/iam/home?#security_credential\n\nWhat is your AWS Access Key ID?\n"
      private: no

    - name: "aws_secret_key"
      prompt: "\nWhat is your AWS Secret Access Key?\n"
      private: no

    - name: "confirmation"
      prompt: "\nSpinUp will now provision your server. This process usually takes anywhere from 5 to 10 minutes on average...\n"

  pre_tasks:
    - name: Set the AWS Region fact
      set_fact:
        aws_region: "{{ regions[aws_region_var] }}"

    - name: Set the AWS VPC ID fact
      set_fact:
        aws_vpc_id: "{{ aws_vpc_id_var }}"
      when: aws_vpc_id_var != ""

    - name: Set the AWS VPC Subnet ID fact
      set_fact:
        aws_vpc_subnet_id: "{{ aws_vpc_subnet_id_var }}"
      when: aws_vpc_subnet_id_var != ""

  roles:
    - genesis-amazon


- include: spinup.yml
