- name: Prepare the new server for Ansible
# ========================================
  hosts: spinup-host
  gather_facts: no

  remote_user: root

  tasks:
    - name: Install Python using a raw SSH command to enable the execution of Ansible modules
      raw: apt update && apt install python -y
      args:
        executable: /bin/bash


- name: Configure the server and install the required software
# ============================================================
  hosts: spinup-host

  remote_user: root

  roles:
    - common
    - ssh
    - ufw
